### ISSUE TITLE
Is it compatible with KubeJS

### ISSUE THREAD

**Issue by ardissaps** [Dragon-Seeker/LoadMyFuckingTags#1]

**Comment by Dragon-Seeker** [comment]
https://user-images.githubusercontent.com/50533513/183263155-3893400a-15f7-4db1-a3b3-8e5d0b8cc3d9.mp4

**Comment by ardissaps** [comment]
> 
> https://user-images.githubusercontent.com/50533513/183263155-3893400a-15f7-4db1-a3b3-8e5d0b8cc3d9.mp4
> 
> 

I tried, but need to know under the hood

**Comment by Dragon-Seeker** [comment]
There is nothing to know, look at the mixins. It works if KubeJS uses vanilla tag code then it should be fine.
