### ISSUE TITLE
L_Enders_Cataclysm 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [Dragon-Seeker/LoadMyFuckingTags#11]
The author of the L_Ender's Cataclysm mod has no comments on CurseForge or the opportunity to write about the error. There is only a Discord channel, maybe there is a Feedback. 

Is this a bug with his mod? Should I write to him?

[21:32:53] [Worker-ResourceReload-11/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag cataclysm:ancient_remnant_target: minecraft:sniffer (from L_Enders_Cataclysm-1.88 -1.19.2.jar)
10239 | [21:32:53] [Worker-ResourceReload-11/ERROR]: [Load My Fucking Tags] Couldn't load certain entries with the tag cataclysm:modern_remnant_target: minecraft:sniffer (from L_Enders_Cataclysm-1.88 -1.19.2.jar)

**Comment by Dragon-Seeker** [comment]
Here is [info](https://github.com/Dragon-Seeker/LoadMyFingTags/blob/3961e898550c4d996199bea0fa408a61e87e8dba/info.md) about what exactly means. It is most likely a bug with the mod but it is not harmful. The modpack being used added LMFT to prevent bigger issues so you can just ignore the error for now.
