### ISSUE TITLE
"By default there is builtin config file that will be generated" - Where is it?

### ISSUE THREAD

**Issue by HatTrkPatrk** [Dragon-Seeker/LoadMyFuckingTags#12]
![image](https://github.com/Dragon-Seeker/LoadMyFingTags/assets/5185596/0fb6b70f-8308-40a5-ae29-73c03892e23e)

I clicked on this and got sent to the Wiki page on this repo, at: https://github.com/Dragon-Seeker/LoadMyFingTags/blob/3961e898550c4d996199bea0fa408a61e87e8dba/info.md

It mentions the following:

> By default there is builtin config file that will be generated if non exist which allows you to disable such by changing "disableIngameError" to "true"

But I don't see that config file in the "config" directory, and I can't seem to locate it anywhere else. I saw a reference to "lmft.json" in the code on here when I checked.

I tried to manually create this file (config/lmft.json) with the following contents:

```
{
  "disableIngameError": true
}
```

But this does not change anything, the message is still shown in-game. So how as a player can I disable this message?

**Comment by Dragon-Seeker** [comment]
What version of the mod are you running? Combined with the specific platform and Minecraft version would be great as I have no bases to help without such.

Furthermore the message is sent from the server so the config must be edited from such not on the users end.

**Comment by HatTrkPatrk** [comment]
I checked the server-side and it does indeed exist there. Sorry about that! And thank you!
