### ISSUE TITLE
[Suggestion] Mod Blacklist

### ISSUE THREAD

**Issue by emihead** [Dragon-Seeker/LoadMyFuckingTags#16]
Hi, I think it'd be useful to have a mod blacklist. Sometimes a mod's tags are of no concern to me and do nothing but get in the way of errors I'm trying to fix (Like Sounds on 1.20, whose devs refuse to take 1.21 items out of the tags on the 1.20 build).

**Comment by Dragon-Seeker** [comment]
I will not be adding a way to silence tag errors, LMFT stops tag-loading failures from breaking an entire tag. The error is a copy of vanilla and are there to get people to fix there mods/datapacks
