### ISSUE TITLE
[Request] Option to disable the warning on the chat

### ISSUE THREAD

**Issue by vico93** [Dragon-Seeker/LoadMyFuckingTags#2]
An option to keep it only on console would be interesting for me at least.

**Comment by Dragon-Seeker** [comment]
An undocumented java arg exists for disabling the Chat output, with the key being: `lmft.disable_error_output`. So within the java args field of the server, you would put `-Dlmft.disable_error_output=true`

**Comment by vico93** [comment]
Okay, thanks for the information!
