### ISSUE TITLE
[Request] Ability to silence the startup message in chat

### ISSUE THREAD

**Issue by LordGideon** [Dragon-Seeker/LoadMyFuckingTags#4]
Greetings! Love this mod - it's solved a lot of interesting conflicts for me. My only complaint about it is that while I think the name is hysterical, the startup message loading each time I play can be a bit grating. Is there anyway to silence the welcome message?

Thanks for the hard work. This mod is a life saver!

**Comment by LordGideon** [comment]
Apologies. Just saw you wrote some instructions on how to perform this task.

**Comment by LordGideon** [comment]
Apologies. Just saw the instructions you provided.

**Comment by Dragon-Seeker** [comment]
Hey, it's all good. Totally forgot to add the link within the Mod Description going over this. In the future, I may see about implementing a simple config loading system for easier disabling of such errors but I manly didn't know at the time how to do such without including a Lib.

**Comment by LordGideon** [comment]
No problem. Your instructions worked perfectly. The mod is fantastic, it's just the name isn't great for my seven year old to see every time the game loads. Hahahahaaaaaaa

"Daddy, what's fucking?"
"Ask your mother. And...uh... let's not go around saying that word, okay?" ;)

**Comment by Dragon-Seeker** [comment]
Honestly understand that such a title can be quite provocative in which I may within the future just calls it LMFT. I could also make sure to have Modmenu hide it as a library mod.

**Comment by Dragon-Seeker** [comment]
Oh... I forgot to censor such ingame. That Is my bad I kinda forgot about such and will release an update with changes.

**Comment by Dragon-Seeker** [comment]
Ok so I added a basic config option for disabling the ingame message for 1.20.1 and censor the foul language. I may think about backporting the such within the future but idk. 6ef396921e61a1f3a9c97d3edf905fd7ff3aec39 and a0224be9bab6b86364974f9af1c93cd9df4ebdd0

**Comment by LordGideon** [comment]
Thanks! Much appreciated!
