### ISSUE TITLE
1.18.2 version of mod Mislabeled on Curseforge

### ISSUE THREAD

**Issue by FoxyFox909** [Dragon-Seeker/LoadMyFuckingTags#5]
[This file](https://www.curseforge.com/minecraft/mc-mods/lmft/files/4687812) is mislabeled as a Forge mod, when it is for Fabric mod.

**Comment by Dragon-Seeker** [comment]
Oh... such has been changed. That's what I get for uploading a mod for 3 versions of Minecraft across 2 differing loads at the same time. Thanks for telling me

**Comment by FoxyFox909** [comment]
Whoah that was fast lol. Appreciated. It was making me have to manually reinstall the mod as it wanted to "update" to the fabric version every time I wanted to update my upcoming Forge modpack's mods, so I reported it lol. But even then I woulda kept updating it manually, lifesaver of a mod you have here.
