### ISSUE TITLE
[1.20.1 Forge] Crash when creating a world

### ISSUE THREAD

**Issue by chorbintime** [Dragon-Seeker/LoadMyFuckingTags#6]
User is on v9 of BMC4 Forge. First person to report this - it is not consistently reproducible across machines but appears to be reproducible for this user 

[crash-2023-08-18_23.16.43-client.txt](https://github.com/Dragon-Seeker/LoadMyFingTags/files/12380929/crash-2023-08-18_23.16.43-client.txt)

**Comment by Dragon-Seeker** [comment]
Hmm quite concerning to say the least since that target references to lambda within the `(Yarn) TagGroupLoader.buildGroup` which is used to capture that has failed... odd that it happens constantly for this user. Ill do some investigating to see if I can find what is making such changes to fail with targeting such

**Comment by Dragon-Seeker** [comment]
It seems that some mod in this list when update to the Users version causes this problem:
 - L_Enders_Cataclysm-1.29-1.20.1.jar
 - corail_woodcutter-1.20.1-3.0.2.jar
 - forge-1.20.1-47.1.44-universal.jar
 - bygonenether-1.3.1-1.20.x.jar

Those versions are only found with the user after comparing to the release version I have downloaded for V9.

**Comment by Dragon-Seeker** [comment]
Ok it seems that forge 47.1.44 just has something going on in the `TagGroupLoader` that mess the lambda up or removes it

**Comment by Dragon-Seeker** [comment]
Ah nuts, Forge patch is completely messing up the Inject I think: https://github.com/MinecraftForge/MinecraftForge/blob/1.20.x/patches/minecraft/net/minecraft/tags/TagLoader.java.patch

**Comment by Dragon-Seeker** [comment]
Ill just have to rewrite the mixin specifically to deal with Forge and release an update for such.

**Comment by Dragon-Seeker** [comment]
Fixed in version 1.0.3: [Link](https://modrinth.com/mod/lmft/version/FMTxW0ZB)
