### ISSUE TITLE
[1.20.1 Forge 47.2.6] Crash on loading in a world or trying to create a new world

### ISSUE THREAD

**Issue by FishingHacks** [Dragon-Seeker/LoadMyFuckingTags#7]
[crash-2023-11-19_17.09.43-client.txt](https://github.com/Dragon-Seeker/LoadMyFingTags/files/13403770/crash-2023-11-19_17.09.43-client.txt)

**Comment by FishingHacks** [comment]
sorry for the low amount of information, but i really cant figure out what the issue is. I just launched the game with lmft, and it still crashed. I am using prism as my launcher, but i dont see how that should affect things

**Comment by Dragon-Seeker** [comment]
Thanks for the heads up about this. It seems that there was a recent bug fix that changed the Set being passed within the needed Mixin which led to a crash due to it not being the proper set type. Should be a simple fix that I can get pushed out tomorrow

**Comment by FishingHacks** [comment]
glad to hear that!

**Comment by Dragon-Seeker** [comment]
Update pushed to modrinth and curseforge
