### ISSUE TITLE
[BUG] 1.18.2 Crash when selecting Mod Icon within Mods Tab

### ISSUE THREAD

**Issue by xFirefalconx** [Dragon-Seeker/LoadMyFuckingTags#8]
Issue description:
Clicked on Mod config inside of Configured (ingame mod to change configs). Game froze and crashed to NEC window. 

Probably not a big issue since not many will do that but hey, maybe it's an oopsie so I thought I report it. 
Not confirmed inside minimal environment (Forge 40.2.14, MC 1.18.2, LMFT 1.0.2, Configured 2.0.1) yet. But if it happens, it's probably worth a look into. 

[latest.log](https://github.com/Dragon-Seeker/LoadMyFingTags/files/13422265/latest.log)
[crash-2023-11-21_05.49.56-client.txt](https://github.com/Dragon-Seeker/LoadMyFingTags/files/13422269/crash-2023-11-21_05.49.56-client.txt)

**Comment by Dragon-Seeker** [comment]
Well for the most part this seems to be a issue either with Forge or Minecraft not liking the path of the mod icon. Such dose not occur on more recent versions of the mod and I am not thinking about back porting a fix at the moment.
